### ISSUE TITLE
Apostrophes are not rendered properly in the e-mails list

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#10]
Wino
![image](https://user-images.githubusercontent.com/43090263/228285330-1ce2349a-f116-493e-b6ff-7c585a24ee5b.png)
Mail for Windows
![image](https://user-images.githubusercontent.com/43090263/228285495-1d5e1009-45e3-403d-ad55-af5789bf966e.png)

**Comment by bkaankose** [comment]
Thanks for reporting this.

There are 2 issues in this context:

- Parsing mail subject
- Parsing the actual HTML body (meaning that your apostrophes in the actual html body has problems as well.)

You figured out the first one, and it's been fixed in the next release preview 1.3 But the second one is weird, because it only  happens when you send mail from Mail for Windows

This message is sent from Outlook Web
![image](https://user-images.githubusercontent.com/12009960/229137207-5c2eb0c8-18f9-45c9-80cc-e4a9b4155ec1.png)

This message is sent from Mail for Windows
![image](https://user-images.githubusercontent.com/12009960/229137288-bdbf4f2f-08d4-4381-81fc-e66fd5853969.png)

Generated HTML body output for the mails sent from MFW (Mail for Windows) by Wino.

```
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=Windows-1252"/>
<meta name="Generator" content="Microsoft Word 15 (filtered medium)"/>
<style><!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
--></style>
</head>
<body lang="EN-US" link="blue" vlink="#954F72" style="word-wrap:break-word" oncontextmenu="return false;">
<div class="WordSection1">
<p class="MsoNormal">    </p>
<p class="MsoNormal"><o:p>&nbsp;</o:p></p>
<p class="MsoNormal">Sent from <a href="https://go.microsoft.com/fwlink/?LinkId=550986">
Mail</a> for Windows</p>
<p class="MsoNormal"><o:p>&nbsp;</o:p></p>
</div>
</body>
</html>

```
There is some encoding problem with this generated body because MFW has no problem parsing the proper html body out of raw mime message.

![image](https://user-images.githubusercontent.com/12009960/229138795-04d8e801-b353-4e8b-9fe3-717066fda2bf.png)

Wino uses this simple [HtmlPreviewVisitor ](https://github.com/jstedfast/MimeKit/blob/master/UnitTests/HtmlPreviewVisitor.cs) from MimeKit to extract html body out of raw mime. Which I believe can be improved with some alternatives later on. At some point in this file, the encoding "**Windows-1252**" can't resolve apostrophes in the HTML.

This is my analysis for this bug as of today, but I think I will get back to this issue once I finish composing :)

**Comment by bkaankose** [comment]
For similar issue

https://github.com/jstedfast/MimeKit/issues/717

**Comment by bkaankose** [comment]
> For similar issue
> 
> [jstedfast/MimeKit#717](https://github.com/jstedfast/MimeKit/issues/717)

Lol actually simpe registration of charset fixed the issue 
![image](https://user-images.githubusercontent.com/12009960/229141658-ee20b099-a793-4439-8c26-731de2f6e6c0.png)

I will label this issue 'fixed' and we can close the bug after testing it on preview 1.3. Thanks! @MarcAnt01
