### ISSUE TITLE
Display the time of reception of an e-mail

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#12]
![image](https://user-images.githubusercontent.com/43090263/228287099-80974e15-d8ec-4b85-9294-797da7284cf3.png)
Using Gmail I cannot see the time of reception of an e-mail which is quite important. I think its design in Mail for Windows could be copied

**Comment by bkaankose** [comment]
Mail app has some logic for displaying time.

Today -> Only time.
Not today and in current week (week starts on Sunday somehow) -> Day abbreviation + short time.
Previous week -> Day abbreviation  + short date
Others -> Long date

This behavior is easy to implement, but I believe always showing message received time is better since the date is already displayed on the header.

I have implemented this feature as the following

![image](https://user-images.githubusercontent.com/12009960/228691613-e0dc0964-1e6d-42af-8657-1747da44ec2d.png)

**Comment by MarcAnt01** [comment]
Honestly I prefer Mail app's logic for the simple reason that I often don't recall the current day🤣🤣

**Comment by MarcAnt01** [comment]
Jokes asides, I would display only the time for e-mails of the same day, for e-mails not older than a week you can keep the date, even though I prefer Mail app implementation

**Comment by bkaankose** [comment]
Let's go one step further and make it configurable in the settings in this menu

![image](https://user-images.githubusercontent.com/12009960/228843621-28d9a83b-89bc-47f4-b318-6ec642af33aa.png)

I will put few options, including the original logic from mail app.

**Comment by MarcAnt01** [comment]
I think can be closed now
