### ISSUE TITLE
E-mails rendered in light mode even though the app is in dark mode

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#13]
I think also the e-mails should be rendered by default according to the system theme

**Comment by bkaankose** [comment]
I have very basic "invert theme" functionality in place, but did not want to include it in Preview 1.2 due to compatibility. I know even the one in Mail & Calendars is not working perfectly at the moment, but mine was performing worse.

There are some web plugins like [Dark Reader](https://github.com/darkreader/darkreader#using-dark-reader-for-a-website) which I think I can implement for WebView2 inside Wino.

Most of the mails nowadays don't follow common practices for theming. Therefore it makes it hard for Wino to detect the mail's intended theme and revert it. Maybe not for Preview 1.3, but this enhancement can be included in  minor bugfix releases for Preview 1.3 later on.
