### ISSUE TITLE
[Proposal] Show unread mails count in sidebar also for folders

### ISSUE THREAD

**Issue by MichalVasut** [bkaankose/Wino-Mail#134]
**Describe the solution you'd like**
Please show count of unread mails in the sidebar also for folders - they are synced correctly, but not showing in the sidebar.

In example I've marked 2 mails as unread in folder `certy` and also 2 mails in `INBOX`. In `INBOX` the count is showing, but not for folders (in example folder `certy`, but this applies  also for other folders in collapsible section `More`)

![image](https://github.com/bkaankose/Wino-Mail/assets/20949562/4ebda5a0-7e1d-4f61-aded-a913e23003c8)

The synchronization of folders is enabled in settings.

**Is your proposal implemented in Windows Mail?**
Yes, this is implemented in Windows Mail

**Additional context**
Nice feature (maybe for another suggestion request) would be to show folders with unread mails also when the `More` section is collapsed.

**Comment by bkaankose** [comment]
Not all folders are enabled by default. I think only Draft and Inbox is marked to display unread count. Maybe a setting per-folder is more ideal to fix this. I assumed that other folders are not so relevant to display unread count, but it might be a need for some users.

I'll include this in the next release.

**Comment by MichalVasut** [comment]
Thanks, (just to clarify) it's relevant when you are receiving lots of mails (therefore categorization into folders) and it's nice when you are notified and view how many new / unread mails are there.

Example - I'm developer and I'm receiving tons of mails from Gitlab, so I don't want to make mess in the inbox, so I redirect them to the folder. At the same time, those mails are useful , because those are notifications baout merge requests, ...

**Comment by bkaankose** [comment]
Folder synchronization option under the account settings are updated as below

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/78c86932-6f15-45ef-9781-4249eef6d88b)

Each folder can be individually marked to show or hide the unread badge. Only draft folder is exception here though. Draft folder will always show the existing draft count instead of unread mail count.

Marking the issue as fixed for now. I'll close the issue once it hits the Store.
