### ISSUE TITLE
Support caching

### ISSUE THREAD

**Issue by MarcAnt01** [bkaankose/Wino-Mail#16]
I expect the app to cache old e-mails.
This is helpful to have the e-mails list loaded at startup and to be able to use the app offline to check older e-mails

**Comment by bkaankose** [comment]
I didn't get what you mean by caching. Can you elaborate? Wino will download last 1000 items per account with full MIME content on initial sync for now.  Downloading full mail boxes for all folders will take so much time otherwise.

I want to enhance search functionality for older mails. Or just download the definition from the mails and download mime content on the fly. Right now what's time consuming is fetching the raw mime content from Outlook. Gmail already works with MIME only.

**Comment by MarcAnt01** [comment]
Nvm, I thought it was not present, but it was probably misbehaving. Now I tried to open it again and it showed the content properly. I just notice that the loading of the mailbox is a bit slow. If I open Mail for Windows it's there after the splash screen

**Comment by MarcAnt01** [comment]
Should I refactor the issue to mention that the mailbox is not loading on start-up or do you prefer me to create an additional issue?

**Comment by bkaankose** [comment]
I think loading of the mailbox is acceptable state at the moment. It may be slower compared to Mail for Windows because they don't have animations. Can you share a video or a gif for launch? Your mailbox should be ready to use in under 2 seconds of time.

**Comment by MarcAnt01** [comment]
Actually I think it's too slow, if the app is without the main content I'd rather to have a delayed splash screen
Video of the delay compared to the mail app https://discord.com/channels/372137812037730304/1075553419303075850/1090661237928513640

**Comment by bkaankose** [comment]
You can see your mails in

**3.5** seconds on Mail for Windows
**4** seconds on Wino.

Mail for Windows loads everything in splash screen, therefore Wino launches faster and loads everything on app shell. I don't think it's worth to invest performance boost for app launch performance at the moment specially to gain half a second.

In Preview 1.3, I will enable proper pre-launch mechanism for Wino. Which will make your items visible instantly, if your operating system decides to give enough resources on OS startup.

https://learn.microsoft.com/en-us/windows/uwp/launch-resume/handle-app-prelaunch

Then since Wino launches faster than Mail for Windows on your machine, you should see your mails instantly.

**Comment by MarcAnt01** [comment]
If you plan to add such option it sounds great
