### ISSUE TITLE
[Bug] CommandBar for non draft emails visual issues.

### ISSUE THREAD

**Issue by Tiktack** [bkaankose/Wino-Mail#165]
**Describe the bug**
CommandBar for non draft emails has a few issues: 

1.  Three dots menu with secondaryCommands ( Currently only "Save As") is not visible if there enough space. 
So, the only way to click save as is to make window smaller to trigger three dots menu appear for PrimaryCommands.
Enough space to render all primaryCommands: 
![image](https://github.com/bkaankose/Wino-Mail/assets/22834937/ef55de34-3e5c-4177-b894-e34c0ef33221)
Not enoush space to render all primaryCommands: 
![image](https://github.com/bkaankose/Wino-Mail/assets/22834937/6515d9bf-bf5d-4b19-8563-1e3cbed89104)

2. When three dots menu expanded click "outside" is not closing it. Maybe it was done intentionally, but for me it looks weird. And it's not consistent with commandBar in Draft email. 
3. Theme button for email rendering is not changing Icon ( it's all the time "Sun" ). 
![image](https://github.com/bkaankose/Wino-Mail/assets/22834937/4d2267cc-d58b-47e4-8d2d-95e5241987f5)
4. Icon in a Theme button is not centered. 
![image](https://github.com/bkaankose/Wino-Mail/assets/22834937/201271b5-e0be-4873-90bb-487228ac09f1)

**Comment by bkaankose** [comment]
Thanks for the report. 

1) is not really a bug because only most commonly used items must be in Primary, rest should not fill up the UI. Therefore 'Save As' belongs to Secondary commands. Also, just secondary commands are designed to be hidden even if there are space in CommandBar.

2) it's weird bug yes.
3) it's a bug. It used to work.
4) it's a bug. Label position is incorrect when the label string is empty.
