### ISSUE TITLE
[Bug]Cannot click "send"

### ISSUE THREAD

**Issue by CanghaiDragon** [bkaankose/Wino-Mail#179]
After click the "New Mail" to write an email, you will disappointingly find it unable to send.

**Comment by bkaankose** [comment]
When you click 'New Mail' a local draft is created. At the same time it's being sent to the mail server. Until server confirms that it's actually created on the server you are not able to send it, thus the send button is disabled.

Current version in the Store is pretty old and has more bugs than Beta version. Could you please confirm this in [Beta version](https://github.com/bkaankose/Wino-Mail/releases)?

**Comment by CanghaiDragon** [comment]
Now the store version is fine and I can send new mail🤣

Unfortunately, the problem remains in the latest preview version:(


Sent from Wino Mail<https://github.com/bkaankose/Wino-Mail/> for Windows

**Comment by bkaankose** [comment]
New version 1.7.2 is released today with new re-worked drafting system. Please give it a try and close the issue if you think it's fixed.

Keep in mind that during the initial synchronization; if you create a draft that button will be disabled until your synchronization is completed. It's because Wino performs tasks immidiately, but waits their responses from the synchronization. Since there can only be 1 synchronization at a time, you must wait for the initial one to complete.

Thanks.
