### ISSUE TITLE
[Bug] Email displaying in wrong account 

### ISSUE THREAD

**Issue by SD777x** [bkaankose/Wino-Mail#193]
**Describe the bug**
When first starting Winomail sometimes I get email from another account inside of the email inbox of a different account which is highlighted.  It seems to happen with sent mail and drafts primarily. 

Also sent mail is being populated in the inbox as the main email in conversations, if you want to match the old MS mail app this should only be shown nested under the first email received.  To clarify the way Winomail displays sent messages in a conversation should be the initiating email be shown and not the latest sent message.  You can directly compare this comparing conversations and how they are listed/nested in the old MS app versus Winomail.  

**Expected behavior**
Email from accounts should stay in that account.

Sent emails should only be displayed nested under the relevant initiating email.

**Screenshots**
Enclosed screenshot, you will note the draft/sent email inside of the first/top email account, which is the highlighted account, but those emails were sent using the account 3rd on the list, so it's showing in the wrong account. 
![Screenshot 2024-05-24 120140](https://github.com/bkaankose/Wino-Mail/assets/36245422/066df92c-0735-4411-a4a7-f234c1740197)

**Additional context**

**Comment by bkaankose** [comment]
This is improved in Beta version, but still buggy. In Beta, you won't see misplaced drafts, but still see some mails going to your listed folder instead of the correct folder.

By default, Wino treats Drafts without checking the assigned folder. Because a draft can be a reply to an existing item on your listed folder. We must check whether if created draft is a reply to any of the listed mail in your listed folder at the moment. This check doesn't exists. Therefore drafts will always be placed as you show in the picture. However, in the next version they won't be placed to a different account for sure :)
