### ISSUE TITLE
[Bug] "Upgrade to Unlimited Accounts" button does nothing when clicked

### ISSUE THREAD

**Issue by MilkTeaCat52** [bkaankose/Wino-Mail#196]
**Describe the bug**
After clicking the "Upgrade to Unlimited Accounts" button, it stays in the "pressed" state for a while, then returns to normal. Nothing else happens, no popup, no redirect to Microsoft store. Sometimes, the mouse cursor turns into the "loading" blue circle, but nothing occurs.

**Expected behavior**
A redirect to the Microsoft store to upgrade to unlimited accounts.

**Screenshots**
![image](https://github.com/bkaankose/Wino-Mail/assets/91018175/3a311963-dd38-4a03-9378-23628eefdbdc)

**Additional context**
I have tried resetting Microsoft store, changing my Windows and Microsoft account region and changing my IP address. None of these have worked.

**Comment by bkaankose** [comment]
I don't think it's Wino related issue. What it does is just trigger Windows APIs to present a purchase dialog for you, which solely Windows handles after that point.

You might have some pending updates on your Windows. I can't debug that unfortunately, but I can assure you that the reason why the dialog is blocked is not because of Wino.

Could you please retry after making sure that you have all the updates on your machine?

**Comment by MilkTeaCat52** [comment]
It was a problem with my system. A component called "Store Experience Host" was missing for some reason. (I only found out this was the problem when I opened the Xbox app, which told me I was missing a system component and helped me install it. I don't get why the MS Store can't check for these things when Xbox can; Windows really is fragmented these days.)
