### ISSUE TITLE
[Bug] Typo in recipients placeholder in composing page

### ISSUE THREAD

**Issue by GreenDragon527** [bkaankose/Wino-Mail#202]
**Describe the bug**
1. When sending an email, manually input addresses don't seem to be acknowledged, only those from the address book. Winomail treats a manual input email address as no address. This seems to be fine if I put someone from my contacts first and then manually input an address after. 

2. Minor typo in the recipients field, adresses missing a 'd'.

**Expected behavior**
I should be allowed to manually type in an email address that isn't in my address book.

**Screenshots**
1.
![image](https://github.com/bkaankose/Wino-Mail/assets/40502690/72cbecd3-f97f-4b93-a184-eefb144a6194)
2.
![image](https://github.com/bkaankose/Wino-Mail/assets/40502690/14bb28b5-2c33-415c-9dad-26280564146d)

**Additional context**

**Comment by bkaankose** [comment]
1. Current version in the Store requires users to hit 'enter' key to validate addresses. This is fixed in the beta release and will be published to Store soon.
2. I will update the translations.

Closing the issue for now since this is very minor thing and requires no code change, but only Crowdin update.

Thank you!
