### ISSUE TITLE
I'm Needing Additional Setup Instructions 

### ISSUE THREAD

**Issue by Davy49** [bkaankose/Wino-Mail#21]
Hello,
Your Wino-Mail application looks to be very promising as well as interesting, my problem is the fact that at least so far I've yet to find any setup instructions. As I'm an older man, it's quite possible that I somehow might have missed seeing them that's why I'm posting this. Thanks in advance for any and all advice I might possibly receive as to get my three active email account's setup properly so I can actually start using this application.

Update: I did in fact discover how to add my email accounts, but I feel like this mail application still needs a bit more polishing so to speak so at least for now I'm uninstalling the app and may try it again in the near future.
David

**Comment by bkaankose** [comment]
Hello David,

Thanks for the feedback. I completely agree with you. Since Wino is still in Preview, I haven't figured out how the setup wizard should look like. Therefore there is only manage accounts page for now to setup your mails.

Also, by no means Wino is a completely mail client for now. As you discovered, some core functionality is lacking still like drafts and composing. I am hoping to finish these features as soon as possible and finally get Wino out of Preview :)

Thanks again for giving a try and hope to see you in public release as well!
