### ISSUE TITLE
[Bug] Gmail doesn't have a dedicated "archived" folder

### ISSUE THREAD

**Issue by AkazaRenn** [bkaankose/Wino-Mail#221]
**Describe the bug**
In 1.7.2.0, to archive an email, we need to select a folder where the email will be moved to, but Gmail doesn't have a dedicated folder for archived emails. Instead, it uses "inbox" and "all (inbox + archived)" for that purpose, thus it makes archiving unavailable for Gmail accounts.

**Expected behavior**
Like the versions before 1.7.2.0, archiving an email of a Gmail account would do the same as its official web client, which makes the email not shown in the "inbox".

**Screenshots**
![image](https://github.com/bkaankose/Wino-Mail/assets/8340896/3f25a67a-6b24-4389-b42c-aae9925fe543)

**Additional context**

**Comment by bkaankose** [comment]
Previously API integration was marking mails as 'archived'. This logic is more generalized in the new version to move them to specific folder. I agree, that functionality is lost for gmail right now.

It'll be better to have it fixed for the next release.

**Comment by bkaankose** [comment]
Can you give this a try onn 1.7.4? I believe this should be fixed.

One thing to note though; archiving on Gmail only removes the 'Inbox' label from the mails. Therefore it's not possible to see the mail you archived in Wino since it doesn't have Unarchive folder or something. It'll be only visible to you on Gmail web portal or All Mails folder probably.
