### ISSUE TITLE
[Proposal] Moving the "Rate Wino" item directly into the "Settings" menu

### ISSUE THREAD

**Issue by Lisa24Jackson** [bkaankose/Wino-Mail#229]
It would be great if you moved the "Rate Wino" item directly to the "Settings" menu. I understand that it somewhat contributes to the app's distribution, but having a separate item on the main panel for it isn't ideal. Also, for simplicity and cleanliness of the app, perhaps it's also worth removing the "Manage Accounts" item, since it's duplicated in "Settings" itself, and making one additional click isn't a problem. Alternatively, you can add a settings button next to the account profile to directly access "Manage Accounts", as shown in the screenshot.

![image](https://github.com/bkaankose/Wino-Mail/assets/155259522/8c14f87b-338f-4f62-943d-31127c320510)

**Comment by bkaankose** [comment]
1) I agree with moving the 'Rate Wino' button from the menu. It's been there for a while. 
2) I stil find Manage Accounts to be useful in the menu because general settings and account settings are highly divided into two parts. For one that needs a quick setup in the application it's quite useful. Especially for elderly people. I agree that it's not something to be used all the time, but until we have a proper "Welcome" setup I want to keep it there.

I liked the settings icon on the menu bar per-account, but it may look quite busy on the screen with accounts more than 3. Plus, when there is an unread icon badge horizontally it will take more space and it won't be tablet friendly to place a small gear icon there.

**Comment by Lisa24Jackson** [comment]
> 1. I agree with moving the 'Rate Wino' button from the menu. It's been there for a while.
> 2. I stil find Manage Accounts to be useful in the menu because general settings and account settings are highly divided into two parts. For one that needs a quick setup in the application it's quite useful. Especially for elderly people. I agree that it's not something to be used all the time, but until we have a proper "Welcome" setup I want to keep it there.
> 
> I liked the settings icon on the menu bar per-account, but it may look quite busy on the screen with accounts more than 3. Plus, when there is an unread icon badge horizontally it will take more space and it won't be tablet friendly to place a small gear icon there.

Accepted. Thanks for the explanation 🙃

**Comment by Tiktack** [comment]
> I liked the settings icon on the menu bar per-account, but it may look quite busy on the screen with accounts more than 3. Plus, when there is an unread icon badge horizontally it will take more space and it won't be tablet friendly to place a small gear icon there.

I think also it's cool idea. And to do not clutter UI it can appear only on hover the same like actions appear for mails ( remove/mark as read/archive)

**Comment by bkaankose** [comment]
> Would it be possible to hide the button if I already rated the app? Not sure if API exposes that information.

API doesn't expose that info, but it's removed from the menu in today's hotfix release (**1.7.3**).

Closing this issue as the patch went live already. Please re-open if you think it's not fixed. @Lisa24Jackson

**Comment by Lisa24Jackson** [comment]
@bkaankose 
That's great, thank you ❤️
