### ISSUE TITLE
[Bug] mail.de IMAP server error - BAD invalid command

### ISSUE THREAD

**Issue by dxsty98** [bkaankose/Wino-Mail#263]
**Describe the bug**
Unfortunately following the 1.7.X update I can't connect my Mail.de email anymore. Connecting to my account via IMAP Server gives the following error message: "The IMAP server replied to the 'ID' command with a 'BAD' response: invalid command

**Expected behavior**
E-Mail account e.G "Dusty@mail.de" should be available to add through managed accounts/Add New Account/IMAP Server

**Screenshot**
![meh](https://github.com/bkaankose/Wino-Mail/assets/73874711/848a2f20-ced5-4301-b74d-49c4d35b6809)

**Protocol**
Connected to imaps://imap.mail.de:993/
S: * OK IMAP4 ready
C: I00000000 CAPABILITY
S: * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE AUTH=PLAIN AUTH=LOGIN
S: I00000000 OK completed
C: I00000001 ID ("version" "1.0" "os" "Windows" "vendor" "Wino")
S: I00000001 BAD invalid command

**Comment by bkaankose** [comment]
I believe this issue is fixed for the upcoming version. 

Context: Most IMAP servers support [ID extension](https://www.rfc-editor.org/rfc/rfc2971.html). Some of  them require it, some of them not. Some of them require it pre-authentication, some of them post-authentication. Some of them return BAD as a response, some of them NO as a response. If the server supports, current version of Wino only handles NO response from the pre-authentication but in your case GMX.de responds as BAD to this call from Wino.

I wanted to create an account on GMX.de for trying out the fix but failed since it requires German mobile phone for registration. However, I may have some workarounds to try this fix.

I am planning to release the new version on Tuesday-Wednesday. Labeling the issue as fixed, will let you know once the new version goes live. Thanks!

**Comment by dxsty98** [comment]
Thanks for the quick response you are awesome

**Comment by bkaankose** [comment]
v1.7.6 is released today. This should be fixed. Please give it a try and close the issue if you think it's fixed. If it's not fixed I might need an actual GMX.de account for trying this out unfortunately.
