### ISSUE TITLE
[Proposal] CLI

### ISSUE THREAD

**Issue by ghost** [bkaankose/Wino-Mail#267]

**Comment by bkaankose** [comment]
Even though I find it quite weird, I understand that some people (specially Linux folks) are interested in CLI mail clients. 

Wino doesn't have CLI, but Wino.Core project is just a .NET Standard library. As you mentioned, Wino.Mail project is the UI wrapper around that library. With slight modifications you can create your own Console application that will work as a CLI. Services you must implement for all functionalities are already abstracted.

I don't think I will ever spend time on creating it myself, but if you will be willing to work on it I am ready to provide support for code changes in the Discord channel if needed. I'd like to keep this repository issues only for end users to provide feedback about the actual app instead of the CLI support.
