### ISSUE TITLE
[Proposal] Add Italian language/translation

### ISSUE THREAD

**Issue by P40L0X** [bkaankose/Wino-Mail#281]
Wino Mail is amazing and already supports many different languages and translations...except Italian, my native language...
Please evaluate also adding it in future versions.

Thank you,
-P

**Comment by bkaankose** [comment]
Looks like most of the Italian strings are already translated in [Crowdin](https://crowdin.com/project/wino-mail).

I will include it in the next release which I'm hoping to release in 3 days. Labeling as fixed.

**Comment by bkaankose** [comment]
This issue is fixed for the next release v.1.8.0.

1.8.0 is released to Beta channel. If you'd like to try that version please [go here](https://github.com/bkaankose/Wino-Mail/releases/tag/v1.8.0) and [follow the instructions here to install](https://learn.microsoft.com/en-us/windows/application-management/sideload-apps-in-windows) until it's released to Store.

**Comment by bkaankose** [comment]
Italian language is released to Microsoft Store with today's 1.9.0 release.

**Comment by P40L0X** [comment]
> Italian language is released to Microsoft Store with today's 1.9.0 release.

Thank you, but days/months names in the center List pane are still translated in English (could also be in other languages as well?)
Could you complete the Italian translation also there?

Thanks,
-P

**Comment by P40L0X** [comment]
> Italian language is released to Microsoft Store with today's 1.9.0 release.

I mean [these](https://i.imgur.com/56lIjO1.png)

Right click pane is also [not translated](https://i.imgur.com/W9hoD2Z.png).
