### ISSUE TITLE
Options grayed out and suggestions

### ISSUE THREAD

**Issue by yatoya** [bkaankose/Wino-Mail#31]
![Zrzut ekranu 2023-08-29 173048](https://github.com/bkaankose/Wino-Mail/assets/24204692/f4685023-c394-4f49-941b-fa293728991b)
All options except Personalization and About are grayed out?
Is that because of early build?
Can you please make adjustable sidebar with mail? Left side with mails is very narrow.
App looks good!

**Comment by bkaankose** [comment]
Thank you for the report and giving Wino a try @yatoya!

Settings are grayed out because they are not implemented yet. v1.6.2 will have a banner to indicate it like this

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/bc62ba98-433d-41c0-8710-f97e839026a8)

I created another issue to track adjustable open menu width in #32 

Closing this one for now.
