### ISSUE TITLE
[Bug] Spaces automatically deleted upon word deletion during message composition

### ISSUE THREAD

**Issue by masrani-zak** [bkaankose/Wino-Mail#353]
When composing a message, deleting a complete word using backspace is also deleting the space right before it and it's bringing the type cursor to be directly adjacent to the previous word. This means every time I delete a word, I have to insert a space after which is driving me nuts as I type.

It seems that this bug has been reported on the old windows mail app.

Running Windows 11 and Wino Mail Version 1.7.8.0.

**Comment by Tiktack** [comment]
Am I correct, when you saying "backspace" removes word+space before you mean "ctrl + backspace"?

**Comment by masrani-zak** [comment]
Nope just backspace deleting the word letter by letter. When the whole word is deleted, the space is then deleted with it automatically.On Sep 7, 2024, at 2:50 AM, Tiktack ***@***.***> wrote:﻿
Am I correct, when you saying "backspace" removes word+space before you mean "ctrl + backspace"?

**Comment by horseshoe107** [comment]
Just confirming that this behaviour is still in v1.9.0

OP is saying that the expected behaviour is for pressing backspace to delete exactly one character. This usually happens, except when you are deleting a character that is preceded by a space. Then, two characters are removed.

For example (imagine that | is the position of the cursor, and with each line we press backspace once):
Two words|
Two word|
Two wor|
Two wo|
Two w|
Two|
Two|

If you start typing from the 2nd last line of the example above, then it is as if the backspace acted twice when you only wanted to press it once. However, there is more unusual behaviour: if you press backspace once more (taking you to the last line of the above example), the cursor stays where it is, as if it is trying to make up for the double backspace.

**Comment by horseshoe107** [comment]
Adding related issue: the same "doubling" behaviour is observed for the Delete key.

For example (again imagine that | is the cursor, with each line we press delete once):
|Two words
|wo words
|o words
|words
|words

**Comment by Tiktack** [comment]
Yes, it's still the same 1.9.0. Should be fixed in a next release.

**Comment by bkaankose** [comment]
New release 1.9.1.0 is released to Store today which should fix this issue. Please re-test with the new version and close the issue if it's all good.

**Comment by horseshoe107** [comment]
It's fixed for me.

**Comment by Tiktack** [comment]
Closing as it is fixed.
