### ISSUE TITLE
[Bug] Webview area jumps on navigation

### ISSUE THREAD

**Issue by Tiktack** [bkaankose/Wino-Mail#371]
**Describe the bug**
When navigation from one email to another, webview jumps. It happens even if previous and next email have absolutely the same height of Top area ( To/Cc/Bcc/Title and so on)

**Expected behavior**
No jumps

https://github.com/user-attachments/assets/d63e2129-d510-425e-b25a-c426ebb70afb

**Comment by bkaankose** [comment]
1
![image](https://github.com/user-attachments/assets/65133070-7cb2-4bff-a9ce-9c9ec6a406e5)

2
![image](https://github.com/user-attachments/assets/6ff3ae75-caed-48e3-a60c-afca942036dd)

This is because To/From/CC are replaced. Until 2. e-mail's recipients are loaded, the height of the dynamic list is 0 on the second picture.

**Comment by bkaankose** [comment]
1.9.2 went live today. Closing as fixed.
