### ISSUE TITLE
[Proposal] Email Sync Delay - Adding push mail

### ISSUE THREAD

**Issue by hellomadworld** [bkaankose/Wino-Mail#452]
I have three accounts in Wino, but they all update and sync more slowly compared to how it was in Windows Mail. Emails arrive 1-2 minutes later. Two of the accounts use IMAP connections, 3th - Gmail default. Wino runs in the background, but even when I'm in the client, emails still don’t arrive immediately. This is not that fastest push like on Wmail. Is it possible to add push mail?

**Comment by bkaankose** [comment]
Instant push notifications are not possible for Wino in Gmail and Microsoft Live accounts for security purposes. The way it works:

1- Wino must create a subscription for you in the provider's server to listen all your Inbox changes.
2- You receive a mail -> provider triggers a signal that notifies Wino.
3- Wino synchronizes.

to make it work; I must know your personal access token personally on the website I'm hosting. This is not something I personally want to handle and is very open for attacks. I also know that most people would not agree to this. Wino Mail only runs on your computer and does not expose your access tokens to other servers.

Only candidate for live changes is IMAP. According to IMAP specs, one can listen to notification changes on the specific folder and get notified if the IMAP server supports that command. This however is not yet implemented in Wino. I delayed it because I'd like to have more performant imap synchronizer in the future, which planning to implement this functionality together.

**Comment by hellomadworld** [comment]
Of course i talked about instant IMAP's push, that have other mail clients.

**Comment by bkaankose** [comment]
I'll create a detailed issue for IMAP improvements next week to track this and link to this issue.
