### ISSUE TITLE
[Bug] IMAP, The remote host forcibly closed an existing connection

### ISSUE THREAD

**Issue by mxdlzg** [bkaankose/Wino-Mail#485]
**Describe the bug**
Wino Mail frequently encounters a "Remote host closed an existing connection" error when attempting to view emails from notifications.
The issue of "Remote host closed an existing connection" only occurs with the 163.com email account (using IMAP), while the Google account (also likely using IMAP) works without problems. This suggests the problem is specific to the 163.com server configuration or interaction with the Wino Mail application.
Furthermore, synchronization with the 163.com account is consistently slow, with the email list taking 5-10 seconds to appear each time Wino Mail is opened.

**Expected behavior**
Email should open and display the inbox quickly (within a second or two), and accessing emails from notifications should be instantaneous and without error.  Both Google and 163 accounts should perform similarly.

**Screenshots**
![image](https://github.com/user-attachments/assets/61abd327-fe7f-4f84-9e36-fb02d1f81fb6)

**Additional context**
[WinoLogs.zip](https://github.com/user-attachments/files/17954916/WinoLogs.zip)

**Comment by chenseanxy** [comment]
I've encountered this in #200, interesting that you're not getting a "UNSAFE LOGIN" error here, as that is pretty consistent with my Netease account. Can you confirm that you're on version 1.9.30? (PS: That fix won't solve this issue but it'll make sure Wino can do any form IMAP operations after a connection reset.

The problem is that Netease doesn't like long-living connections, and kicks you off after you're connected for a little while, and Wino would have to reestablish connections the next time it tries to sync.

I'm thinking two long term solutions:

1. Very dirty catch-all retry, just retry from the top level sync request and thus everything down the chain (acquiring connections, sending commands, etc) are all retried. Could be destructive and make the cost double for all sync requests if there's something wrong with the setup.
2. Short-lived connections, not sure how standard this is for email apps, but we detect setups like this somehow (like maintaining a connection reset counter?), and then switch to short connections where it gets closed after a request is done, and every subsequent request we start a new one.

Might need @bkaankose 's input on this

**Comment by chenseanxy** [comment]
But this is another issue and has nothing to do with the sync behaviour:

> with the email list taking 5-10 seconds to appear each time Wino Mail is opened

If you don't need email threading (shows the chain of all replies in a thread), turn it off in Settings -> Message List -> Conversation Threading. The reason IMAP is different from Gmail is that Gmail handles things quite differently through their APIs. There were some discussions in the summer about baking this in during synchornization, but I can't seem to find it. Relevant PR #173

**Comment by mxdlzg** [comment]
Thanks chenseanxy for the quick response and proposed solutions. I'm using the latest version from the store (1.9.30) and haven't received an "UNSAFE LOGIN" error.

Regarding the slow email list loading (5-10 seconds), I've disabled "Conversation Threading" (Settings -> Message List -> Conversation Threading) as suggested, and this issue is now **resolved** .

However, the "Remote host closed an existing connection" error persists and only occurs with my 163.com email account. I prefer solution 2 (short connections) as it's likely more efficient than solution 1 (retries).

**Comment by mxdlzg** [comment]
I've noticed this error frequently occurs when the UI initially opens. This makes me wonder if there's a connection between the UI and the error. Perhaps a slight delay in initiating the synchronization, similar to how Windows Mail handles it (with a few seconds delay between UI operation and synchronization), could mitigate this issue.

**Comment by chenseanxy** [comment]
> I've noticed this error frequently occurs when the UI initially opens. This makes me wonder if there's a connection between the UI and the error. Perhaps a slight delay in initiating the synchronization, similar to how Windows Mail handles it (with a few seconds delay between UI operation and synchronization), could mitigate this issue.

Afaik the only connection between these two is that the UI would try to send a sync request to Wino Server which would then try to fetch new emails, it's only then that the OS would realize that the connection has already been closed. The main issue is still that Netease kicks you off connections constantly. That hasn't been much of a bother for me as long as it eventually syncs, but I suppose it could be annoying when that happens constantly.
