### ISSUE TITLE
Can't add a SMPT service

### ISSUE THREAD

**Issue by Pietro228** [bkaankose/Wino-Mail#54]
Hi,

I use [https://napoveda.seznam.cz/cz/imap-pop3-smtp/](this) email service and I just get this content dialog for ever:

![obrazek](https://github.com/bkaankose/Wino-Mail/assets/53868994/f0c5124b-1cd9-40d7-a437-318644c391c1)

I finally wanted to use this email manager because of the SMPT protocol, but it still doesn't as expected

**Comment by bkaankose** [comment]
To test this provider I've created a new account

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/c62d42a4-8663-4b24-889c-5b469539e4f7)

looks like it's working with correct configuration. However, there is a bug in the current version that any exception encountered will not be reported to the users. Probably that's why you got stucked in the setup dialog.

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/682f3603-91e6-441b-b70f-78bff929ba70)

Your SMTP port should be 465, and if you have 2 factor authentication enabled you must provide the password from this page

https://napoveda.seznam.cz/cz/login/postovni-programy-caldav-dvoufazove-overeni/

**Comment by Pietro228** [comment]
Oh sorry, I just forgot what password I used for authentification :D I used this email on an iPhone Mail few months ago, so I was confused why it doesn't work here.

Thank you for helping me out! Have a great day :)
