### ISSUE TITLE
Any ETA for open-sourcing?

### ISSUE THREAD

**Issue by Benjin** [bkaankose/Wino-Mail#61]
There are some fit/finish/usability bugs that I'd love to help patch up.  Happy to also contribute to a private repo if you want to set up the permissions.

**Comment by bkaankose** [comment]
This is open for discussion actually. I want the monetization to keep going, but also want to open source for people to contribute if they want to. However, making money out of somebody else's work is something I don't want to do. It's kind of conflicting in its own nature at this point.

I am open for ideas.

**Comment by Benjin** [comment]
I think keeping the base version free then charging to unlock the more advanced features is completely fine for an open source project; just make sure the license you choose allows for it.

The advantage of it being open-source is that if anyone truly feels like it's against the OSS credo, then can clone the repo, edit a value to unlock the paid features, and recompile it themselves.  That feels like an acceptable balance to me.

**Comment by clragon** [comment]
I will subscribe to this issue to be notified when this project goes open source, if ever,
since all the other issues regarding this topic have been closed.

**Comment by HenrikZabel** [comment]
@bkaankose You could make it open source, but not allow others to collaborate. Then it's 100% your work, but anyone can see the source code.

Alternatively, you could simply ask for donations. I would be willing to donate if the project becomes open source. I think many others do too

**Comment by bkaankose** [comment]
What do you think about [CC BY-NC-ND ](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en)

Basically **you can**
- Use the code for educational purposes.
- Modify the code for your personal + non-commercial use.

**but you can't**

- Use the code for commercial purposes.
- Build another mail client on top of this and distribute it for financial gain.

GitHub sponsors or PayPal donations are not valid for me because most people use this application are not developers, they are end users that come directly from Microsoft Store. I don't have plans to introduce paid features into Wino anymore. I find Unlimited Accounts add-on sufficient enough for everybody. Plus, it's one-time payment with no subscription.

For contributions, I don't know what to do :) Nobody should feel or obligated to fix or improve the codebase. Code will be here to ; improve performance, design new features according to the codebase, write test cases, update translations etc. I can not give all contributors the equality they deserve in this effort. Therefore, it will solely by their own willing to do such activities with no expectation other than a mention in the patch/release notes.

**Comment by miyoyo** [comment]
Creative commons themselves discourage the use of their licenses for code:
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

You would be better served making this proprietary source-available software using your own license for it (or a similar source sharing license such as the ones from Apple, Microsoft, Thales, etc), however, given the restrictions given in your message, this should be fine, as it doesn't seem like the objective is to be open source

**Comment by MisterSausage** [comment]
I feel horrible saying this, because you've obviously spent a huge amount of time on this project, you seem justifiably proud of what you've achieved single-handedly, and you receive (at least some level of) income from selling the unlimited accounts add-on, but I really wish you'd open source the whole thing and be done with the whole question. Sorry to be so blunt.

There's a huge need for a native, straightforward and user friendly Windows email client, and that need will increase a thousand-fold when Microsoft finally obsoletes the inbox Windows Mail app.

Making Wino Mail open source will take a lot of the development burden off your back, because I'm quite certain many (including me) will be keen to contribute. It'll leave you able to take whatever development role you want in the future - from full-on benevolent dictator, to principal developer, to simply just keeping an eye on the project and having the final say on pull requests. It also gives users assurance that there's a future for the app if you decide to walk away in the future, for whatever reason.

Keep scope for donations - after all, a certain level of funding is required even if only for certificates, etc - and maybe note in writing in README.md that you'll keep 75% of all donations for the next five years or something.

**Comment by bkaankose** [comment]
> I feel horrible saying this, because you've obviously spent a huge amount of time on this project, you seem justifiably proud of what you've achieved single-handedly, and you receive (at least some level of) income from selling the unlimited accounts add-on, but I really wish you'd open source the whole thing and be done with the whole question. Sorry to be so blunt.
> 
> There's a huge need for a native, straightforward and user friendly Windows email client, and that need will increase a thousand-fold when Microsoft finally obsoletes the inbox Windows Mail app.
> 
> Making Wino Mail open source will take a lot of the development burden off your back, because I'm quite certain many (including me) will be keen to contribute. It'll leave you able to take whatever development role you want in the future - from full-on benevolent dictator, to principal developer, to simply just keeping an eye on the project and having the final say on pull requests. It also gives users assurance that there's a future for the app if you decide to walk away in the future, for whatever reason.
> 
> Keep scope for donations - after all, a certain level of funding is required even if only for certificates, etc - and maybe note in writing in README.md that you'll keep 75% of all donations for the next five years or something.

You are mostly right and believe me, I want to be over with this as well :) I just don't want to see the same project as "**Kino Mail**" in Microsoft Store with unlimited accounts add-on removed. There has to be some sort of mechanism to prevent this because I am pretty sure it is going to happen.

As long as you are not literally copying this work to create a mail client that serves to end user I am fine with everything.

- You are working in a company that needs Graph API, Gmail API or IMAP sync mails for the people in the company or any other purpose that does not build free (or paid) mail client? Sure go ahead. If this code is going to make life easier in any way use it.
- You are a developer but you don't want to buy the add-on for your additional accounts? Remove the price flag, build yourself and use it.

2 profile above I described is not my target monetization audience. I just want my years of work to help people at some point; whether it's the way app shell is constructed, it's the theming, it's the handling of navigation or literally in any way that they need in their own project, but their usage of the code should not sabotage my monetization target.

In the end I'm a developer works 9 - 5 at corporation that started this project as a side project, and believe me, when I started to work on Wino, Microsoft didn't have any plans to deprecate Windows Mail yet :) That boosted the idea of "**need**". Paint.NET was also a need for years, but it's still closed source and free. You pay for the automatic updates and contribute to the developer who worked on this for years. Something becoming a need for somebody doesn't prove much here. My goal was never to satisfy in-house app users due to Microsoft's bad decision making.

I'm not really looking to sweep out all the juicy dollars out of people's pocket here:) Maybe we should just go with MIT and see what happens. If there will be a pure damage with bad intentions later on we can find another ways to continue.

**Comment by MisterSausage** [comment]
> I just don't want to see the same project as "**Kino Mail**" in Microsoft Store with unlimited accounts add-on removed. There has to be some sort of mechanism to prevent this because I am pretty sure it is going to happen.

Unfortunately, as Wino Mail gets more popular, I think this is inevitable, and it'll happen even it isn't not open sourced.

.NET decompiles so cleanly that it'd likely only take an day's work for someone experienced to take the package and create a buildable version on their own machine.

**Comment by dongle-the-gadget** [comment]
> .NET decompiles so cleanly that it'd likely only take a day's work for someone experienced to take the package and create a buildable version on their own machine.

As far as I’m aware though, Wino currently uses .NET Native rather than .NET Core. It isn’t meant to be an obfuscation layer, but it does deter people who aren’t extremely committed (which I doubt those people are)

**Comment by bkaankose** [comment]
> > I just don't want to see the same project as "**Kino Mail**" in Microsoft Store with unlimited accounts add-on removed. There has to be some sort of mechanism to prevent this because I am pretty sure it is going to happen.
> 
> Unfortunately, as Wino Mail gets more popular, I think this is inevitable, and it'll happen even it it's not open sourced.
> 
> .NET decompiles so cleanly that it'd likely only take a day's work for someone experienced to take the package and create a buildable version on their own machine.

UWP apps are compiled with .NET Native, which is harder to analyze/re-compile. What you talk about is cracking. If someone can literally decompile the whole released UWP app from Store, modify it to remove a single add on, re-compile it and publish it to Microsoft Store (which Store has policies to prevent it) they can already e-mail me and I will provide them the source code :) It's not an easy task.

The person who can do that don't need my code and that's not even my point.

**Comment by nreh** [comment]
As a worst case, I guess you could have a small group of contributors in a private repo. Not ideal, but at the very least it's a step in the right direction.

Another idea is to extract some logic into a separate project/repo and make it open source while keeping the more difficult to clone stuff in a private repo. That way, while people can see and edit features - for instance something like the settings page - they won't be able to just do `git pull` and publish a clone.

The latter I've seen somewhat done, but I have no idea if it's possible with your codebase without completely rewriting it so only you'd know.

**Comment by bkaankose** [comment]
> As a worst case, I guess you could have a small group of contributors in a private repo. Not ideal, but at the very least it's a step in the right direction.
> 
> Another idea is to extract some logic into a separate project/repo and make it open source while keeping the more difficult to clone stuff in a private repo. That way, while people can see and edit features - for instance something like the settings page - they won't be able to just do `git pull` and publish a clone.
> 
> The latter I've seen somewhat done, but I have no idea if it's possible with your codebase without completely rewriting it so only you'd know.

Wino is abstracted into layers:

- Domain: Literally every model including SQLite entities without any logic.
- Core: .NET Standard library that does the synchronization using Domain.
- View Models: NET Standard library for app's view models. VMs are not in the App layer to support multiple platforms later on like mobile.
- App - UWP app itself.

You remove one out of this equation and it's all gone :) Plus there are stuff like Azure App Registration and Gmail API keys, which I spent a good amount of time to be compliant with Google. You can create your own API key for the Gmail, but it may not be the same as using Wino's internal key for some scenarios. This is another aspect of open sourcing this project. 

Open sourcing:
- Domain: Nothing useful there.
- Core: People can work on synchronizer and authenticator bugs, but there won't be a presentation layer (App). So maybe we can overcome by this using a Console app, just for seeing the improvement.
- View Models: Without the domain and core, it does not mean much. Couple bugs and improvements can be worked on without presentation layer.
- App: This is also useless without the rest. Just UI improvements can be worked on.

So it's either take all or nothing to be efficient with improvements.

**Comment by HenrikZabel** [comment]
> they can already e-mail me and I will provide them the source code :)

I emailed you a few days ago. Are you still willing to do this?

**Comment by bkaankose** [comment]
> > they can already e-mail me and I will provide them the source code :)
> 
> I emailed you a few days ago. Are you still willing to do this?

That was an exaggeration for people who can already crack released UWP application from store, modify and re-publish the cracked version. 🥲

**Comment by HenrikZabel** [comment]
Okay too bad, I thought you were already willing to share the code in principle, but didn't want it to be publicly visible on GitHub without more.

**Comment by Catscratch** [comment]
What's with donations? Like Signal does it. It's open-source and for free and everyone can pay whatever he wants on a regular base.

There is already a "sponsor" button at the end of this page where everyone can directly donate something for you.

**Comment by bkaankose** [comment]
I decided to open source the app under GPL-3.

Initial sources do not belong to the application released in Store for now. I've been working on a big patch for couple months already and it's still **not finished**. However, once finished it'll be released to Store from this repository.

Public keys I use for the store version will also be removed from the source. I will prepare a guide to create your own keys for Outlook and Google synchronizers. IMAP synchronizer is not affected by this.

Store version will keep unlimited accounts add-on for the reasons I explained in this discussion. Code will be here for anybody to unlock the paid add on and keep using for their own.

**Comment by clragon** [comment]
Awesome, great to hear that.

**Comment by Tiktack** [comment]
It's awesome mail client. Any news about open sourcing it?

**Comment by Benjin** [comment]
Any updates?  I'm looking forward to digging into a few bugs/minor features myself!

**Comment by bkaankose** [comment]
> Any updates? I'm looking forward to digging into a few bugs/minor features myself!

It's been rough few months lately unfortunately. Things I planned last year did not fit into my current schedule, but that's alright. I finished most of the work for the new version. Just need to prepare the following things:

- Contribution guideline
- Cleaning up the obsolete code
- Removal of the personal API keys
- Communicating the original source code and published app code differences because the version I will share the sources for is not yet released in the Store.

I will have some time off this weekend to finish up the above tasks. Then a new journey will start for all of us 👍🏻

**Comment by MichalVasut** [comment]
I see you're releasing new versions, bug fixes, and beta versions, but do you have any time left for preparing to publish the code? Any updates on this?

**Comment by bkaankose** [comment]
Wino Mail is now open source 🎉 🎉

Thanks everybody! It somehow pleases me to close this issue in the end :)

- Before you dive into the code, I recommend everybody to read the [contribution guideline](https://github.com/bkaankose/Wino-Mail/blob/main/CONTRIBUTING.md) first. You will find good information to get you started with the project.
- License, Readme and Contributing files are updated for the project.
- Code in the repository is up to date, but keep in mind that the released sources belong to beta release (1.7.0), not the Store version.

Happy hacking😊

**Comment by 14142000** [comment]
It's a double edged sword, you can open source it and risk people forking a truly free version, at the same time you can get the benefits of help maintaining the app and get timely bugfixes that actually make it worth paying for, so you dont have situations like for me right now the app is completely unusable because it gets stuck at "Authenticating with Gmail" stage.

Why would I pay for an app that regularly breaks so catastrophically? It really is going to be a balancing act of Value vs competition from forks.  people will pay for the original if it genuinely stays competitive. But realistically thats just software in a nutshell.
