### ISSUE TITLE
[Feature Request] Calendar

### ISSUE THREAD

**Issue by GreenDragon527** [bkaankose/Wino-Mail#68]
Is wino mail going to fully replace the mail and calendar app but also including a calendar or is that going to be a separate app? Just asking 🙂

**Comment by Benjin** [comment]
Actually, I'd request the exact opposite: the calendar should be a separate app because emails and schedule aren't inherently linked concepts.  I think Microsoft joins the two because the Outlook team thinks is the most important app in anyone's life, and they want people to live inside it.  Personally, I'd rather sign into each app individually.

The apps can already talk to each other via `mailto://` and `cal://` links.

**Comment by bkaankose** [comment]
> Actually, I'd propose the exact opposite: the calendar should be a separate app (as they are on macOS, iOS, Android, and Gmail) because emails and schedule aren't inherently linked concepts. I think Microsoft joins the two because the Outlook team thinks it's the most important app in anyone's life, and they want people to live inside it. Personally, I'd rather sign into each app individually, and be able to manage them separately.
> 
> The apps can already talk to each other via `mailto://` and `cal://` links when they need to.

I don't think communication is an issue between apps. At least small talk let's say. Both can activate each other with protocols but they can't share the common data. Wino Mail will synchronize mails, detect some calendar events and save it to local database. This can be only accessed by Mail, not the Calendar.

Microsoft can package multiple UWP applications into a single package and let them share files. I don't think it's possible without completely switching to WinAppSDK.

**Comment by bkaankose** [comment]
By the way, Calendar part of Wino will be completely fine without an account connection. Even though they will live in the same app, as long as users link an account to calendar events it'll be fine.

**Comment by Benjin** [comment]
Wouldn't Wino Mail detect calendar events in emails and instead push them to the Exchange/Google calendar feed associated with that account?  Then the (hypothetical separate) calendar app would sync from there.  I feel like Wino Mail already treats the server as the "source of truth" for mail, so why not calendar as well, thus decreasing the reliance on the local db?

**Comment by Benjin** [comment]
Thinking more about what I hate about Win32 Outlook, liked about the retired Windows Mail/Calendar apps, and hate about the new Outlook.com wrapper app is that the email and the calendar are the same app window.  So I suppose my requests for a calendar experience aren't so much that they're separate app packages, but:

1. Have Mail and Calendar be separate windows that can opened/closed moved around independently from each other
2. Ability to pin Mail and Calendar as separate shortcuts on the taskbar/start menu/desktop
3. Ability to have some accounts only for email, some accounts only for calendar.  Note: this just for UX display; I'm okay with a "mail-only" account still requesting all permissions (including Calendar) from Exchange/Google.
4. Ability to hide shortcuts to the other "app" to clean-up visual clutter:

  ![image](https://github.com/bkaankose/Wino-Mail/assets/1609827/348bd624-ead7-4aa4-9645-b278892a7663)

Whether (1) can be done depends on how the code's set up and which framework you're using, but the other three should be pretty easy.

**Comment by bkaankose** [comment]
Those are great points and more or less we share the same idea. I would love to have the separate apps with all points you mentioned.

The technical challenge here is Mail & Calendars use Windows integrated accounts to work with. You register your account to not to the app, but actually to Windows itself and all apps read from there. That's how an account registered in Mail can be picked up by Calendar. Wino works with a local SQLite database that is placed in the app's local state directory, which can't be accessed by some other UWP apps due to sandboxing. (I still see this sandbox thing as a benefit btw.)

Another problem with the accounts is that Wino supports API integration as well. So for Outlook and Gmail accounts, you can't have them integrated with Windows.

Issues related to accounts might be resolved with Credential locker and use of Windows Credential Manager though. This requires a good amount of refactoring under the hood, considering the approach is fine to continue with. I still need to check whether it's possible to share credentials using Credential Manager between 2 UWP apps.

Accounts are one part of the problem as well. What about user settings? Themes? Users must be able to import all of these in one go without having issues. I think this can be handled via protocol activation of apps, but it's still a challenge.

These are the main points of having separate apps. On the other hand, I can get rid of all of these problems really quickly by having all the apps in 1 shared container. Calendar might be launched in separate App Window for supported devices or in the same window. Different notification types (event or mail) can launch the same app but start with different Frames based on the notification type. You can select whether you want to start with calendar or mail by default once you launch Wino. You can show/hide un-installed apps (like calendar,contacts,people etc.) if you want to. You can disable/enable mail or calendar synchronization for some of the accounts.

So most of it can be get rid of by alternative approaches to do stuff. Only thing you can't do technically is to pin them separately to the taskbar.

This topic is a good candidate to do a big spike on in the future :) I'm open for more discussions on this topic and appreciate all feedback.

**Comment by bkaankose** [comment]
https://learn.microsoft.com/en-us/windows/uwp/launch-resume/extend-your-app-with-services-extensions-packages

This page is helpful for package & resource sharing between apps released by the same author. Sharing here for reference later on.

**Comment by Benjin** [comment]
Thanks for the detailed explanation :) I'm glad to hear we have similar visions.  I'd be perfectly happy with a combined app with separate AppWindows.

> Only thing you can't do technically is pin them separately to the taskbar

I poked around this a bit, and think I found a solution.  I can create shortcuts to store apps from `Ctrl` + `R`: `shell:AppsFolder`, but I couldn't edit launch args (textbox disabled).  However, apps can set an [execution aliases](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#elements-and-attributes-of-this-extension) to get a simple `.exe` in my PATH, then I can create shortcuts off of that with different arguments.

I was able to successfully pin multiple shortcuts for the Spotify store app (which has an execution alias `spotify.exe`) with different args (normal and `--minimized`).  So I think it's possible as long as you give yourself an execution alias and the app can take in execution args.  E.g.:

`WinoMail.exe [--calendar] [--mail]` with a default to wherever if none are specified.

**Comment by bkaankose** [comment]
@Benjin I managed to find a way to share data between two apps seamlessly. So they can be 2 separate apps that can have a shared folder.

I created a new discussion for calendar. Let's continue sharing ideas under that.

https://github.com/bkaankose/Wino-Mail/discussions/85
