### ISSUE TITLE
Inbox Synchronize intervals?

### ISSUE THREAD

**Issue by gslance** [bkaankose/Wino-Mail#80]
Unclear when mailbox does an automatic synchronize with server, seems new emails come in after I manually press the synchronize button. Can settings be exposed, per mailbox, to adjust synchronize times like the old Outlook app?

In addition, a button to synchronize all mailboxes at once would be nice.

**Comment by 17blue17** [comment]
same question how often does it sync?

**Comment by bkaankose** [comment]
There are 2 background tasks that control the synchronization.

- Every 15 minutes will do Inbox sync for all accounts.
- All folder sync when you logon to Windows.

Now the problem here is that background tasks in UWP must be energy efficient. Windows may decide to cancel or not run one or more of these tasks for any given time. I am still experimenting couple things to make it more reliable, but if you want to explicitly allow Wino to support background tasks more reliable way:

1- Right click Wino and go to settings

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/9ec945a6-14d5-4d1f-8107-2db3711dbf7b)

2- Make sure app can "**Always**" run in the background instead of Power optimized

![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/eb839128-73d5-4b07-8b59-9287aeecf143)

3- Optionally you can setup Wino to launch on Startup. It will launch Wino minimized on Windows logon, which I believe will help background sync to run better.

**Comment by 17blue17** [comment]
thank you for the information and support.

**Comment by AkazaRenn** [comment]
Mail and Calendar allows syncing "as item arrives", I'm wondering if it's possible for Wino to implement that?
<img width="344" alt="Screenshot 2023-12-16 195555" src="https://github.com/bkaankose/Wino-Mail/assets/8340896/2673fc8b-c148-4217-b0cb-8bf5bd062b22">

**Comment by bkaankose** [comment]
> Mail and Calendar allows syncing "as items arrive", I'm wondering if it's possible for Wino to implement that? <img alt="Screenshot 2023-12-16 195555" width="344" src="https://private-user-images.githubusercontent.com/8340896/291021872-2673fc8b-c148-4217-b0cb-8bf5bd062b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NzU0ODAsIm5iZiI6MTcwMjc3NTE4MCwicGF0aCI6Ii84MzQwODk2LzI5MTAyMTg3Mi0yNjczZmM4Yi1jMTQ4LTQyMTctYjBjYi04YmY1YmQwNjJiMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTdUMDEwNjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODJhMzgwYjI2NDc3NjFiZjFhY2NhM2YwYzg5NTExNTNkNzRmMzEzYWM2YWJkNjY0OTMwYjU3YzQ3MTM1NjM3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jKBsrFFzsa-1UaAs0joaGe9h46BVnOU2qDWW8YKzjBw">

Everything is possible with **runFullTrust** capability. Right now I'm maintaining 3 different synchronizers. Outlook API, Gmail API and IMAP/SMTP. All of these have their own implementation to speed up things and support different features like Focused inbox for Outlook or Label colors for Gmail.

If I were to refactor wino core (library that handles synchronization) I would just abstract authentication into 3 and only go for IMAP. I'm actually thinking about that for a while. With good planning this can be achieved. Imap synchronizer will be the most stable and only one that does all. It can keep the connection alive and receive mails as they arrive. If the app is closed, an app companion living on system tray can handle the connection.

The app became from Outlook > Gmail > IMAP. That's why it's a challenge to shift things right now. Also runFullTrust will indicate users that Wino can use all of their system resources during install. That's also something I want to avoid.

Options
1) **Only runFullTrust**

Move background synchronization smaller app companion. Make it synchronize accounts every 1,2,3 or x minutes. We can go below 15 minutes.

2) **runFullTrust  + IMAP** 

Get rid of MS Graph and Gmail SDK. Users won't have Focused inbox for Outlook. Category folders and label colors for Gmail. Potentially slower synchronization for Gmail because Gmail API is very smart about sending the changes only. I don't think it'll be faster for imap sync. Listen to Inbox changes with imap connection -> get the mails as they arrive from app companion that runs with fullTrust.

3) Ditch UWP and go for WinAppSDK

Migrate app to WinUI3 + WinAppSDK. I did this in the past. Everything runs fine, but startup performance is not instant. Right now Wino's launch performance is not something I want to give away to be honest. This migration will also make Wino not compatible with other UWP platforms like Xbox. Now who needs a mail app on Xbox? I don't know. It's not a big thing but still a thing. Technically Wino can even launch on Hololens, but yeah... Who cares :)

4) Push notifications with API subscriptions

Outlook and Gmail API support webhooks for changes on specific folders, but they can't send this info to local devices. My web server must have it and deliver it to you. For Wino to have this, I need to have your access token in my server. This is not ideal and a big security flaw + something that I can't manage. So technically possible, but it's not an option on the table :)

**Comment by AkazaRenn** [comment]
@bkaankose Thank you for the thorough explanation! Seems like `Push notifications with API subscriptions` is the most efficient yet powerful way to do that, but would cause some security concerns. As a workaround, would it be possible that users may deploy webservers with access tokens of their own, and make them sending notifications to Wino? Just my two cents!

**Comment by AkazaRenn** [comment]
Of course, the best solution would be to let Gmail support pushing updates to local devices. I was reading [the `watch` API provided by Gmail](https://developers.google.com/gmail/api/guides/push), it seems like a REST call from the client to Google, that might be usable without a server in the middle. Everyone gets 10 GB data per month for Google Cloud Pub/Sub, that should be quite enough for regular usages. It would be fantastic to have in the future if possible. Users will create Pub/Sub topics of their own, and provide that to Wino for subscription.

**Comment by yakamoz423** [comment]
@bkaankose Is there any way to tell the sync task to fetch not only inbox but also all folders? Especially when opening the app.

**Comment by bkaankose** [comment]
> @bkaankose Is there any way to tell the sync task to fetch not only inbox but also all folders? Especially when opening the app.

There is no such thing right now but I will implement it for the next version.

**Comment by AkazaRenn** [comment]
@bkaankose if we are going to have a companion for receiving pushes, maybe we don't have to give up on Outlook/Gmail SDK? We can let the companion be the listener of the push, just like IMAP idle. But if you find it too much work, starting with IMAP only is still very very good to have! And I personally don't mind having the whole app running but minimized if it can receive the emails in real time.

**Comment by bkaankose** [comment]
This effort is being tracked on #270 going forward.

Closing as duplicate.
