### ISSUE TITLE
Some UI suggestions for future app versions

### ISSUE THREAD

**Issue by RSM9** [bkaankose/Wino-Mail#95]
Currently using Wino Mail version 1.6.12.0 (MS Store)

Some suggestions to consider for future updates (may take a while to make these changes, and I see some have been raised previously):

1. The **search bar should start with a capital 'S'**, as it is with Outlook 365 (also try to perhaps make it consistent - if a folder is empty, such a junk mail, 'this' should start with a capital 'T')
2. The **search box needs to be slightly wider** - the left edge of the box lines up with the mail list pane, but the right edge lines up with the right edge of the three dots below it (should line up with the right edge of the mail list pane instead) - _this discrepancy is visible most easily when no e-mail is selected_ - further, perhaps you may want to re-consider the rounded corners (looks different to the mail list pane's rounded corners)
3. The **mail list should have a scroll bar** (as in Outlook 365, preferably a small overlay one) - I can scroll using the middle button of my mouse, but most of Windows uses scroll bars.
4. The left side bar (where it says the e-mail address, Inbox, Donations, etc.) is too wide - look at the proportions (especially in split-screen mode) - I am using the small setting for the mail list pane, but the reading pane still could be made wider in split-screen mode by **making the left side bar slightly narrower** (there is too much wasted space) - - I have at QHD monitor at 150% scaling, but really it is the left side bar that looks out of place a little (compare it to the settings app or Outlook 365, which have narrower side panels)
5. The default setting for the mail list pane makes the reading pane too narrow (you could change the default size of the mail list pane, whilst also making the left side bar narrower)
6. A **feature to select the first e-mail in the list** (without marking it as read of course) would enhance the app also (I see that you are working on this for later)
7. Some less important features may be to allow using the Aptos font for sending e-mails, whilst making HTML e-mails display a sans-serif font (already raised and if not possible then far from necessary), and a back button for the personalisation and settings may be helpful - apart from that, only the bugs of the app crashing when sending e-mails or receiving a notification are what need to be worked on
8. You may even want to consider changing the app title (on the app list only) to WinoMail, given that most e-mail clients are only one-word long (if you are ever thinking of changing the logo, a slightly different shade of blue, and a smaller, less visible white letter would be an improvement)

**Comment by bkaankose** [comment]
All the issues I said "Fixed" under are either fixed in current version or next version which will be released in February.

1- Capital "S" was a discussion before in Discord. Folks suggested as well, but I find it disturbing to the eyes. Maybe it's only me, but with capital Search it looks really weird with all the preview texts under that line. Maybe we can do a survey in Discord to decide this later on.
2- Fixed in February.
3- Fixed in February.
4- This is already adjustable now. You can drag the pane left or right to adjust yourself.
5- It has the same size as Windows Mail. Default size is not any different. As a policy, I tend to keep everything as similar as possible to Windows Mail by default.
6- This is already adjustable as well. You can mark it as read automatically on selection or not take an action.
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/27f8b397-b154-4d95-beb1-ebcd6e3cecc0)
7- Yeah back button would be nice for the pages that have breadcrumb navigation but it requires fundamental changes in Wino's navigation service.
8- Name will be better as it is right now, since I'll start working on Wino Calendar as well. Eventually this can turn into a set of apps that start with Wino. For the logo, yes you are right. I am still working on it and the next version which will be released in February will have the new logo for the app and Store.

**Comment by RSM9** [comment]
Thanks

I know you have discussed this before, but is there any way to make HTML e-mails display a different font to the current one (e.g. swap times new roman out with segoe ui or aptos)?

Outlook 365 and the native mail app seem to be able to render HTML e-mails with a sans serif font, though Wino Mail cannot. This difference is rendering of such e-mails is perhaps the main downside of the app, when compared to the native Mail (the top is WIno, and the bottom image is the native Mail app).


<img width="777" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/107066760/539a7efd-5e69-4d47-9467-ec4408f96adc">

<img width="748" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/107066760/83341f7c-aed1-4023-b967-d29214ab3666">


Finally, I do not seem to be able to delete a custom theme (there does not seem to be an option to). Although this issue is insignificant (and I use the default theme), some wallpapers seem to not work well with the dark theme (see below).
![Uploading image.png…]()

**Comment by bkaankose** [comment]
- I think changing the default font is one of the most requested things at the moment. I will see what I can do through WebView2.
- Deleting or editing custom theme is not implemented yet.
- This bug is something that I am aware of. It happens when you set your Windows theme to Light but Application Theme in Wino to Dark.
- One principle I follow for the development is to use original framework control templates as much as possible. There are very little amount of custom controls or templates in Wino. Anything you see is mostly comes from the original templates. Radical changes like moving icon to the other side or manipulating the control layout is discouraged. This way maintainability of the design is preserved, and we receive the updates immediately as they arrive either to the nuget packages or Windows SDK they come from.

**Comment by RSM9** [comment]
Another very minor issue (which you may already be working on) is the strange tool-bar bit. I am not especially keen on the sync button icon (as compared to the native Mail app), perhaps a the thickness of the font looks quite different to the 'mark' button.

The 'mark' button lacks a hover description, and the tiny arrow next to the three-dots is unnecessary (either enlarge the three dots, or replace it with a larger arrow-head, of the same design).

Additionally, if you change the 's' to 'S' in the search box, the 'up to date' bit should be capitalised at the start for consistency.

Finally, some sort of last synced feature may be a useful one (not necessary though and make take some _time_ to implement).

<img width="248" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/107066760/3b048739-c790-47b3-9b78-a01f4fecd8e8">

<img width="133" alt="image" src="https://github.com/bkaankose/Wino-Mail/assets/107066760/8126f0d8-58fd-4b99-8977-c311f52f073d">

**Comment by RSM9** [comment]
I posted my comment before I saw your response (I see that some changes to the icon layout is difficult, and it is not that important anyway to change those elements).

One thing I would add is that if you do change the font, it would be better not to use Calibri (the font looks to small for text at the default size, as you may have noticed in the message you replied to).

**Comment by RSM9** [comment]
Another two observations:

- [ ] You could add a feature to increase the font size when sending a message (you probably have already thought about this.
- [ ] More importantly, an e-mail cannot be sent without a subject (you could add a prompt as with Outlook 365, etc.), but still allow such e-mails to be sent.

**Comment by bkaankose** [comment]
Following items are fixed for the next version in Februrary.
- Command bar icon sizing and their localized toolbar descriptions.
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/a5bd6a58-77ea-4630-83c0-7f694c681e30)

- Deleting custom themes
- Confirmation before sending a mail without a subject.
- Changing the default font/font size for reader. I think the default was 'serif'. Now it's Arial. Aptos is not released yet as far as I know, and I don't know its licensing. Also Helvetica is not a free font I can embed into Wino. Therefore Aptos and Helvetica will not be included in this version.
![image](https://github.com/bkaankose/Wino-Mail/assets/12009960/67ab5c38-9581-4063-987a-99262b957e74)

It's sometimes hard to track for myself since I use GitHub as backlog as well. Therefore I'll label this issue as fixed as the following updates are done yesterday.

Please open a separate issue for each feedback if you'd like to have further discussions.

Thank you for the great feedback @RSM9

**Comment by bkaankose** [comment]
Closing this outdated issue since most of the suggestions are already included in the latest builds.
